# Use the correct Node.js 20 Alpine image tag
FROM node:20-alpine3.19

# Set the working directory
WORKDIR /app

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy other files
COPY tsconfig.json ./
COPY next.config.mjs ./
COPY postcss.config.mjs ./
COPY tailwind.config.ts ./
COPY src ./src
COPY public/ ./public

#optional
COPY service-worker.js ./service-worker.js

# Expose the application's port
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]
